email:
  address: ""  # Will be loaded from YAHOO_EMAIL env var
  password: ""  # Will be loaded from YAHOO_APP_PASSWORD env var
  imap_server: "imap.mail.yahoo.com"  # Will be loaded from IMAP_SERVER env var
database:
  host: ""  # Will be loaded from POSTGRES_HOST env var
  port: 5432  # Will be loaded from POSTGRES_PORT env var
  dbname: ""  # Will be loaded from POSTGRES_DB env var
  user: ""  # Will be loaded from POSTGRES_USER env var
  password: ""  # Will be loaded from POSTGRES_PASSWORD env var
app:
  debug: false  # Will be loaded from FLASK_DEBUG env var
  host: "0.0.0.0"
  port: 5050 