email:
  address: "your_email@example.com"
  password: "your_app_password"
  imap_server: "imap.mail.yahoo.com"
database:
  host: "localhost"
  port: 5432
  dbname: "emaildb"
  user: "bankuser"
  password: "bankpass"
app:
  debug: true
  host: "0.0.0.0"
  port: 5000 