services:
  postgres:
    image: postgres:16
    container_name: bank-postgres
    environment:
      POSTGRES_PASSWORD: bankpass
      POSTGRES_DB: emaildb
      POSTGRES_USER: bankuser
    volumes:
      - /data01/postgres:/var/lib/postgresql/data
    ports:
      - "5432:5432"
    networks:
      - bank_network
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U bankuser"]
      interval: 10s
      timeout: 5s
      retries: 5

  flask_app:
    build: .
    container_name: flask_email_fetcher
    environment:
      - POSTGRES_HOST=postgres
      - POSTGRES_PORT=5432
      - POSTGRES_DB=emaildb
      - POSTGRES_USER=bankuser
      - POSTGRES_PASSWORD=bankpass
    depends_on:
      postgres:
        condition: service_healthy
    command: >
      sh -c "sleep 5 && python fetch_emails.py"
    ports:
      - "5000:5000"
    networks:
      - bank_network

networks:
  bank_network:
    driver: bridge
